/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.geektrust.tameofthrones;

import java.io.IOException;
import java.util.List;

import static com.geektrust.tameofthrones.utils.MiscUtils.extractMessagesFromFile;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println(args.length > 0
                ? new App().checkForAlliancesUsingMessagesFromFile(args[0])
                : "Please specify file with messages from kingdoms."
        );
    }

    public String checkForAlliancesUsingMessagesFromFile(String filePathContainingKingdomsMessages) throws IOException {
        return checkForAlliances(extractMessagesFromFile(filePathContainingKingdomsMessages));
    }

    public String checkForAlliances(List<String> messagesFromOtherKingdoms) {
        return new AllianceFinder().checkForAlliances(messagesFromOtherKingdoms);
    }

}
