/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.problemsolving.geektrust.tameofthrones;

import com.google.common.collect.ImmutableList;
import org.junit.Test;

import java.io.IOException;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class TameOfThronesMainTest {
    public static final String SUCCESSFUL_OUTPUT = "SPACE AIR LAND ICE";
    TameOfThronesMain classUnderTest = new TameOfThronesMain();

    @Test
    public void testInputFromFile() throws IOException {
        String commandFilePath = "src/main/resources/input/sample.txt";
        runTest(commandFilePath, SUCCESSFUL_OUTPUT);
    }

    @Test
    public void testMeetingAllAllies() throws IOException {
        ImmutableList<String> arguments = ImmutableList.of("AIR ROZO", "LAND FAIJWJSOOFAMAU", "ICE STHSTSTVSASOS");
        runTest(arguments, SUCCESSFUL_OUTPUT);
    }

    @Test
    public void testMissingOneAllySupport() throws IOException {
        ImmutableList<String> arguments = ImmutableList.of("AIR RMZM", "LAND FAIJWJSOOFAMAU", "ICE STHSTSTVSASOS");
        runTest(arguments, "NONE");
    }

    @Test
    public void testNoAlliesAtAll() throws IOException {
        ImmutableList<String> arguments = ImmutableList.of("AIR RMZM", "LAND FAJJWJSOOFAMAU", "ICE STHSTSTVSBSOS");
        runTest(arguments, "NONE");
    }

    private void runTest(List<String> args, String expected) throws IOException {
        assertExpectation(expected, classUnderTest.processMessages(args));
    }

    private void runTest(String args, String expected) throws IOException {
        assertExpectation(expected, classUnderTest.processInputFromFile(args));
    }

    private void assertExpectation(String expected, String generated) {
        assertNotNull("Result should not not be null.", generated);
        assertEquals("Result should match the expected string.", expected, generated);
    }
}
